#! /bin/sh


xrandr --output HDMI-1 --primary --right-of DVI-D-1 

bspc wm -O HDMI-1 DVI-D-1

pgrep -x sxhkd > /dev/null || sxhkd &


#bspc monitor -d I II III IV V VI VII VIII IX X

bspc monitor HDMI-1 -d I II III IV
bspc monitor DVI-D-1 -d V VI VII VIII

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

/home/ansh/.config/polybar/launch.sh &
xinput set-prop 10 289 -0.3 &
picom --experimental-backends &
feh --bg-scale ~/Pictures/Wallpapers/tokyo-night02.png &
xsetroot -cursor_name left_ptr &
lxpolkit &
